x-common: &common
  ulimits:
    nofile:
      soft: 1048576
      hard: 1048576
  restart: unless-stopped
  networks:
    - remnawave-network

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: 5

configs:
  caddy:
    content: |
      http://localhost:3010 {
        reverse_proxy remnawave-subscription-page:3010 {
          header_up X-Forwarded-For {remote_host}
          header_up X-Forwarded-Proto https
        }
      }

services:
  remnawave:
    image: remnawave/backend:2
    container_name: remnawave
    hostname: remnawave
    <<: [*common, *logging]
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@remnawave-db:5432/postgres
      - REDIS_SOCKET=/var/run/valkey/valkey.sock
      - APP_SECRET="test123123test321424test"
      - SUB_PUBLIC_DOMAIN=localhost:3010/randomstring
      - FRONT_END_DOMAIN=*
      - METRICS_USER=user
      - METRICS_PASS=password
    volumes:
      - valkey-socket:/var/run/valkey
    ports:
      - 127.0.0.1:3000:3000
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3001/health']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      remnawave-db:
        condition: service_healthy
      remnawave-redis:
        condition: service_healthy
    command: 'pm2-runtime start ecosystem.config.js --env development'

  remnawave-subscription-page:
    image: remnawave/subscription-page:latest
    container_name: remnawave-subscription-page
    hostname: remnawave-subscription-page
    <<: [*common, *logging]
    environment:
      - REMNAWAVE_PANEL_URL=http://remnawave:3000
      - REMNAWAVE_API_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNmVlZGI3NjctZDkwMy00NDFiLTk0NGMtZGQ1MjMyOWE5MzkwIiwidXNlcm5hbWUiOm51bGwsInJvbGUiOiJBUEkiLCJpYXQiOjE3ODQyOTY3NDYsImV4cCI6MTA0MjQyMTAzNDZ9.R9UJ1V_PKaP3K1EWrlOxRgaRuHevdq5ErnZhhpZoHr4
      - CUSTOM_SUB_PREFIX=randomstring
      - NODE_ENV=development

  caddy:  
    image: caddy:alpine
    <<: [*common, *logging]
    ports:  
      - '127.0.0.1:3010:3010'
    configs:
      - source: caddy
        target: /etc/caddy/Caddyfile

  remnawave-db:
    image: postgres:18.4
    container_name: remnawave-db
    hostname: remnawave-db
    shm_size: 512mb
    <<: [*common, *logging]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - TZ=UTC # DO NOT CHANGE DATABASE TIMEZONE. IT MUST BE UTC.
    ports:
      - 127.0.0.1:6767:5432
    volumes:
      - remnawave-db-data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d postgres']
      interval: 3s
      timeout: 10s
      retries: 3

  remnawave-redis:
    image: valkey/valkey:9-alpine
    container_name: remnawave-redis
    hostname: remnawave-redis
    <<: [*common, *logging]
    volumes:
      - valkey-socket:/var/run/valkey
    command: >
      valkey-server
      --save ""
      --appendonly no
      --maxmemory-policy noeviction
      --loglevel warning
      --unixsocket /var/run/valkey/valkey.sock
      --unixsocketperm 777
      --port 0
    healthcheck:
      test: ['CMD', 'valkey-cli', '-s', '/var/run/valkey/valkey.sock', 'ping']
      interval: 3s
      timeout: 3s
      retries: 3

  

networks:
  remnawave-network:
    name: remnawave-network
    driver: bridge
    external: false

volumes:
  remnawave-db-data:
    name: remnawave-db-data
    driver: local
    external: false
  valkey-socket:
    name: valkey-socket
    driver: local
    external: false
