[project]
name = "subscription-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "outbound-models",
]

[tool.uv.workspace]
members = [
    "outbound-models",
]

[tool.uv.sources]
outbound-models = { workspace = true, editable = true }

[dependency-groups]
dev = [
    "ruff>=0.15.15",
    "ty>=0.0.40",
]

[tool.ruff]
line-length = 120
