/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  GetUsersApiUsersGetParams,
  HTTPValidationError,
  PageUsers,
  UserCreateRequest,
  UserUpdateRequest,
  Users
} from '../../models';

import { customFetch } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Create
 */
export type createApiUsersPostResponse201 = {
  data: Users
  status: 201
}

export type createApiUsersPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createApiUsersPostResponseSuccess = (createApiUsersPostResponse201) & {
  headers: Headers;
};
export type createApiUsersPostResponseError = (createApiUsersPostResponse422) & {
  headers: Headers;
};

export type createApiUsersPostResponse = (createApiUsersPostResponseSuccess | createApiUsersPostResponseError)

export const getCreateApiUsersPostUrl = () => {




  return `/api/users/`
}

export const createApiUsersPost = async (userCreateRequest: UserCreateRequest, options?: RequestInit): Promise<createApiUsersPostResponse> => {

  return customFetch<createApiUsersPostResponse>(getCreateApiUsersPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userCreateRequest,)
  }
);}




export const getCreateApiUsersPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createApiUsersPost>>, TError,{data: UserCreateRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof createApiUsersPost>>, TError,{data: UserCreateRequest}, TContext> => {

const mutationKey = ['createApiUsersPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createApiUsersPost>>, {data: UserCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  createApiUsersPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateApiUsersPostMutationResult = NonNullable<Awaited<ReturnType<typeof createApiUsersPost>>>
    export type CreateApiUsersPostMutationBody = UserCreateRequest
    export type CreateApiUsersPostMutationError = HTTPValidationError

    /**
 * @summary Create
 */
export const createCreateApiUsersPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createApiUsersPost>>, TError,{data: UserCreateRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof createApiUsersPost>>,
        TError,
        {data: UserCreateRequest},
        TContext
      > => {
      return createMutation(() => ({ ...getCreateApiUsersPostMutationOptions(options?.()) }), queryClient);
    }
    /**
 * @summary Get Users
 */
export type getUsersApiUsersGetResponse200 = {
  data: PageUsers
  status: 200
}

export type getUsersApiUsersGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getUsersApiUsersGetResponseSuccess = (getUsersApiUsersGetResponse200) & {
  headers: Headers;
};
export type getUsersApiUsersGetResponseError = (getUsersApiUsersGetResponse422) & {
  headers: Headers;
};

export type getUsersApiUsersGetResponse = (getUsersApiUsersGetResponseSuccess | getUsersApiUsersGetResponseError)

export const getGetUsersApiUsersGetUrl = (params?: GetUsersApiUsersGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/users/?${stringifiedParams}` : `/api/users/`
}

export const getUsersApiUsersGet = async (params?: GetUsersApiUsersGetParams, options?: RequestInit): Promise<getUsersApiUsersGetResponse> => {

  return customFetch<getUsersApiUsersGetResponse>(getGetUsersApiUsersGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsersApiUsersGetQueryKey = (params?: GetUsersApiUsersGetParams,) => {
    return [
    `/api/users/`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetUsersApiUsersGetQueryOptions = <TData = Awaited<ReturnType<typeof getUsersApiUsersGet>>, TError = HTTPValidationError>(params?: GetUsersApiUsersGetParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getUsersApiUsersGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersApiUsersGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersApiUsersGet>>> = ({ signal }) => getUsersApiUsersGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getUsersApiUsersGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersApiUsersGetQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersApiUsersGet>>>
export type GetUsersApiUsersGetQueryError = HTTPValidationError


/**
 * @summary Get Users
 */

export function createGetUsersApiUsersGet<TData = Awaited<ReturnType<typeof getUsersApiUsersGet>>, TError = HTTPValidationError>(
 params?: () =>  GetUsersApiUsersGetParams, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getUsersApiUsersGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getGetUsersApiUsersGetQueryOptions(params?.(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}






/**
 * @summary Update
 */
export type updateApiUsersUserIdPatchResponse200 = {
  data: Users
  status: 200
}

export type updateApiUsersUserIdPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateApiUsersUserIdPatchResponseSuccess = (updateApiUsersUserIdPatchResponse200) & {
  headers: Headers;
};
export type updateApiUsersUserIdPatchResponseError = (updateApiUsersUserIdPatchResponse422) & {
  headers: Headers;
};

export type updateApiUsersUserIdPatchResponse = (updateApiUsersUserIdPatchResponseSuccess | updateApiUsersUserIdPatchResponseError)

export const getUpdateApiUsersUserIdPatchUrl = (userId: number,) => {




  return `/api/users/${userId}`
}

export const updateApiUsersUserIdPatch = async (userId: number,
    userUpdateRequest: UserUpdateRequest, options?: RequestInit): Promise<updateApiUsersUserIdPatchResponse> => {

  return customFetch<updateApiUsersUserIdPatchResponse>(getUpdateApiUsersUserIdPatchUrl(userId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userUpdateRequest,)
  }
);}




export const getUpdateApiUsersUserIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof updateApiUsersUserIdPatch>>, TError,{userId: number;data: UserUpdateRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof updateApiUsersUserIdPatch>>, TError,{userId: number;data: UserUpdateRequest}, TContext> => {

const mutationKey = ['updateApiUsersUserIdPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateApiUsersUserIdPatch>>, {userId: number;data: UserUpdateRequest}> = (props) => {
          const {userId,data} = props ?? {};

          return  updateApiUsersUserIdPatch(userId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateApiUsersUserIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateApiUsersUserIdPatch>>>
    export type UpdateApiUsersUserIdPatchMutationBody = UserUpdateRequest
    export type UpdateApiUsersUserIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update
 */
export const createUpdateApiUsersUserIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof updateApiUsersUserIdPatch>>, TError,{userId: number;data: UserUpdateRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof updateApiUsersUserIdPatch>>,
        TError,
        {userId: number;data: UserUpdateRequest},
        TContext
      > => {
      return createMutation(() => ({ ...getUpdateApiUsersUserIdPatchMutationOptions(options?.()) }), queryClient);
    }
    /**
 * @summary Delete
 */
export type deleteApiUsersUserIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteApiUsersUserIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteApiUsersUserIdDeleteResponseSuccess = (deleteApiUsersUserIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteApiUsersUserIdDeleteResponseError = (deleteApiUsersUserIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteApiUsersUserIdDeleteResponse = (deleteApiUsersUserIdDeleteResponseSuccess | deleteApiUsersUserIdDeleteResponseError)

export const getDeleteApiUsersUserIdDeleteUrl = (userId: number,) => {




  return `/api/users/${userId}`
}

export const deleteApiUsersUserIdDelete = async (userId: number, options?: RequestInit): Promise<deleteApiUsersUserIdDeleteResponse> => {

  return customFetch<deleteApiUsersUserIdDeleteResponse>(getDeleteApiUsersUserIdDeleteUrl(userId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteApiUsersUserIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteApiUsersUserIdDelete>>, TError,{userId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof deleteApiUsersUserIdDelete>>, TError,{userId: number}, TContext> => {

const mutationKey = ['deleteApiUsersUserIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiUsersUserIdDelete>>, {userId: number}> = (props) => {
          const {userId} = props ?? {};

          return  deleteApiUsersUserIdDelete(userId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiUsersUserIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiUsersUserIdDelete>>>

    export type DeleteApiUsersUserIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete
 */
export const createDeleteApiUsersUserIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteApiUsersUserIdDelete>>, TError,{userId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof deleteApiUsersUserIdDelete>>,
        TError,
        {userId: number},
        TContext
      > => {
      return createMutation(() => ({ ...getDeleteApiUsersUserIdDeleteMutationOptions(options?.()) }), queryClient);
    }
