/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

/**
 * @summary Create
 */
export const createApiUsersPostBodyUsernameMin = 3;
export const createApiUsersPostBodyUsernameMax = 40;

export const createApiUsersPostBodyDescriptionMax = 400;

export const createApiUsersPostBodyEnabledDefault = true;

export const CreateApiUsersPostBody = zod.object({
	username: zod.string().min(createApiUsersPostBodyUsernameMin).max(createApiUsersPostBodyUsernameMax),
	description: zod.string().min(1).max(createApiUsersPostBodyDescriptionMax),
	expire_time: zod.iso.datetime({ offset: true }),
	enabled: zod.boolean().default(createApiUsersPostBodyEnabledDefault)
});

/**
 * @summary Get Users
 */
export const getUsersApiUsersGetQueryPageDefault = 1;

export const getUsersApiUsersGetQuerySizeDefault = 50;
export const getUsersApiUsersGetQuerySizeMax = 100;

export const GetUsersApiUsersGetQueryParams = zod.object({
	page: zod.number().min(1).default(getUsersApiUsersGetQueryPageDefault).describe('Page number'),
	size: zod
		.number()
		.min(1)
		.max(getUsersApiUsersGetQuerySizeMax)
		.default(getUsersApiUsersGetQuerySizeDefault)
		.describe('Page size')
});

export const getUsersApiUsersGetResponseItemsItemUsernameMin = 3;
export const getUsersApiUsersGetResponseItemsItemUsernameMax = 40;

export const getUsersApiUsersGetResponseItemsItemDescriptionDefault = ``;
export const getUsersApiUsersGetResponseItemsItemDescriptionMax = 400;

export const getUsersApiUsersGetResponseItemsItemEnabledDefault = true;
export const getUsersApiUsersGetResponseTotalMin = 0;

export const getUsersApiUsersGetResponsePagesMin = 0;

export const GetUsersApiUsersGetResponse = zod.object({
	items: zod.array(
		zod.object({
			id: zod.union([zod.number(), zod.null()]).optional(),
			username: zod
				.string()
				.min(getUsersApiUsersGetResponseItemsItemUsernameMin)
				.max(getUsersApiUsersGetResponseItemsItemUsernameMax),
			description: zod
				.string()
				.max(getUsersApiUsersGetResponseItemsItemDescriptionMax)
				.default(getUsersApiUsersGetResponseItemsItemDescriptionDefault),
			expire_time: zod.iso.datetime({ offset: true }),
			enabled: zod.boolean().default(getUsersApiUsersGetResponseItemsItemEnabledDefault)
		})
	),
	total: zod.number().min(getUsersApiUsersGetResponseTotalMin),
	page: zod.number().min(1),
	size: zod.number().min(1),
	pages: zod.number().min(getUsersApiUsersGetResponsePagesMin)
});

/**
 * @summary Update
 */
export const UpdateApiUsersUserIdPatchParams = zod.object({
	user_id: zod.number()
});

export const updateApiUsersUserIdPatchBodyUsernameOneMin = 3;
export const updateApiUsersUserIdPatchBodyUsernameOneMax = 40;

export const updateApiUsersUserIdPatchBodyDescriptionOneMax = 400;

export const UpdateApiUsersUserIdPatchBody = zod.object({
	username: zod
		.union([
			zod.string().min(updateApiUsersUserIdPatchBodyUsernameOneMin).max(updateApiUsersUserIdPatchBodyUsernameOneMax),
			zod.null()
		])
		.optional(),
	description: zod
		.union([zod.string().min(1).max(updateApiUsersUserIdPatchBodyDescriptionOneMax), zod.null()])
		.optional(),
	expire_time: zod.union([zod.iso.datetime({ offset: true }), zod.null()]).optional(),
	enabled: zod.union([zod.boolean(), zod.null()]).optional()
});

export const updateApiUsersUserIdPatchResponseUsernameMin = 3;
export const updateApiUsersUserIdPatchResponseUsernameMax = 40;

export const updateApiUsersUserIdPatchResponseDescriptionDefault = ``;
export const updateApiUsersUserIdPatchResponseDescriptionMax = 400;

export const updateApiUsersUserIdPatchResponseEnabledDefault = true;

export const UpdateApiUsersUserIdPatchResponse = zod.object({
	id: zod.union([zod.number(), zod.null()]).optional(),
	username: zod
		.string()
		.min(updateApiUsersUserIdPatchResponseUsernameMin)
		.max(updateApiUsersUserIdPatchResponseUsernameMax),
	description: zod
		.string()
		.max(updateApiUsersUserIdPatchResponseDescriptionMax)
		.default(updateApiUsersUserIdPatchResponseDescriptionDefault),
	expire_time: zod.iso.datetime({ offset: true }),
	enabled: zod.boolean().default(updateApiUsersUserIdPatchResponseEnabledDefault)
});

/**
 * @summary Delete
 */
export const DeleteApiUsersUserIdDeleteParams = zod.object({
	user_id: zod.number()
});
