/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  HTTPValidationError
} from '../../models';

import { customFetch } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Protected Get
 */
export type protectedGetApiTestProtectedGetGetResponse200 = {
  data: unknown
  status: 200
}

export type protectedGetApiTestProtectedGetGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type protectedGetApiTestProtectedGetGetResponseSuccess = (protectedGetApiTestProtectedGetGetResponse200) & {
  headers: Headers;
};
export type protectedGetApiTestProtectedGetGetResponseError = (protectedGetApiTestProtectedGetGetResponse422) & {
  headers: Headers;
};

export type protectedGetApiTestProtectedGetGetResponse = (protectedGetApiTestProtectedGetGetResponseSuccess | protectedGetApiTestProtectedGetGetResponseError)

export const getProtectedGetApiTestProtectedGetGetUrl = () => {




  return `/api/test/protected_get`
}

export const protectedGetApiTestProtectedGetGet = async ( options?: RequestInit): Promise<protectedGetApiTestProtectedGetGetResponse> => {

  return customFetch<protectedGetApiTestProtectedGetGetResponse>(getProtectedGetApiTestProtectedGetGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getProtectedGetApiTestProtectedGetGetQueryKey = () => {
    return [
    `/api/test/protected_get`
    ] as const;
    }


export const getProtectedGetApiTestProtectedGetGetQueryOptions = <TData = Awaited<ReturnType<typeof protectedGetApiTestProtectedGetGet>>, TError = HTTPValidationError>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof protectedGetApiTestProtectedGetGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProtectedGetApiTestProtectedGetGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof protectedGetApiTestProtectedGetGet>>> = ({ signal }) => protectedGetApiTestProtectedGetGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof protectedGetApiTestProtectedGetGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProtectedGetApiTestProtectedGetGetQueryResult = NonNullable<Awaited<ReturnType<typeof protectedGetApiTestProtectedGetGet>>>
export type ProtectedGetApiTestProtectedGetGetQueryError = HTTPValidationError


/**
 * @summary Protected Get
 */

export function createProtectedGetApiTestProtectedGetGet<TData = Awaited<ReturnType<typeof protectedGetApiTestProtectedGetGet>>, TError = HTTPValidationError>(
  options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof protectedGetApiTestProtectedGetGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getProtectedGetApiTestProtectedGetGetQueryOptions(options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}






/**
 * @summary Protected Post
 */
export type protectedPostApiTestProtectedPostPostResponse200 = {
  data: unknown
  status: 200
}

export type protectedPostApiTestProtectedPostPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type protectedPostApiTestProtectedPostPostResponseSuccess = (protectedPostApiTestProtectedPostPostResponse200) & {
  headers: Headers;
};
export type protectedPostApiTestProtectedPostPostResponseError = (protectedPostApiTestProtectedPostPostResponse422) & {
  headers: Headers;
};

export type protectedPostApiTestProtectedPostPostResponse = (protectedPostApiTestProtectedPostPostResponseSuccess | protectedPostApiTestProtectedPostPostResponseError)

export const getProtectedPostApiTestProtectedPostPostUrl = () => {




  return `/api/test/protected_post`
}

export const protectedPostApiTestProtectedPostPost = async ( options?: RequestInit): Promise<protectedPostApiTestProtectedPostPostResponse> => {

  return customFetch<protectedPostApiTestProtectedPostPostResponse>(getProtectedPostApiTestProtectedPostPostUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getProtectedPostApiTestProtectedPostPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof protectedPostApiTestProtectedPostPost>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof protectedPostApiTestProtectedPostPost>>, TError,void, TContext> => {

const mutationKey = ['protectedPostApiTestProtectedPostPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof protectedPostApiTestProtectedPostPost>>, void> = () => {


          return  protectedPostApiTestProtectedPostPost(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProtectedPostApiTestProtectedPostPostMutationResult = NonNullable<Awaited<ReturnType<typeof protectedPostApiTestProtectedPostPost>>>

    export type ProtectedPostApiTestProtectedPostPostMutationError = HTTPValidationError

    /**
 * @summary Protected Post
 */
export const createProtectedPostApiTestProtectedPostPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof protectedPostApiTestProtectedPostPost>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof protectedPostApiTestProtectedPostPost>>,
        TError,
        void,
        TContext
      > => {
      return createMutation(() => ({ ...getProtectedPostApiTestProtectedPostPostMutationOptions(options?.()) }), queryClient);
    }
