"""init

Revision ID: b5461c89e140
Revises:
Create Date: 2026-04-26 23:14:46.337905

"""

import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b5461c89e140"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("password_version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admins")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=400), nullable=False),
        sa.Column("expire_time", sa.DateTime(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "vpnproviders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
        sa.Column("show_name", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vpnproviders")),
    )
    op.create_table(
        "vpnservers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("original_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
        sa.Column("link", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["vpnproviders.id"], name=op.f("fk_vpnservers_provider_id_vpnproviders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vpnservers")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vpnservers")
    op.drop_table("vpnproviders")
    op.drop_table("users")
    op.drop_table("admins")
    # ### end Alembic commands ###
