"""add vpnservers and vpnproviders

Revision ID: f7eb216dca5a
Revises: b480b8c309a6
Create Date: 2026-04-26 16:10:31.977627

"""

import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f7eb216dca5a"
down_revision: Union[str, Sequence[str], None] = "b480b8c309a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vpnproviders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
        sa.Column("show_name", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vpnproviders")),
    )
    op.create_table(
        "vpnservers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("original_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
        sa.Column("link", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["vpnproviders.id"], name=op.f("fk_vpnservers_provider_id_vpnproviders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vpnservers")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vpnservers")
    op.drop_table("vpnproviders")
    # ### end Alembic commands ###
