/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type GetUsersApiUsersGetParams = {
	/**
	 * Page number
	 * @minimum 1
	 */
	page?: number;
	/**
	 * Page size
	 * @minimum 1
	 * @maximum 100
	 */
	size?: number;
};
