/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Users } from './users';

export interface PageUsers {
	items: Users[];
	/** @minimum 0 */
	total: number;
	/** @minimum 1 */
	page: number;
	/** @minimum 1 */
	size: number;
	/** @minimum 0 */
	pages: number;
}
