/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface RegisterRequest {
	/**
	 * @minLength 3
	 * @maxLength 40
	 */
	username: string;
	/**
	 * @minLength 8
	 * @maxLength 200
	 */
	password: string;
}
