/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface UserCreateRequest {
	/**
	 * @minLength 3
	 * @maxLength 40
	 */
	username: string;
	/**
	 * @minLength 1
	 * @maxLength 400
	 */
	description: string;
	expire_time: string;
	enabled?: boolean;
}
