/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface UserUpdateRequest {
	username?: string | null;
	description?: string | null;
	expire_time?: string | null;
	enabled?: boolean | null;
}
