/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  createMutation
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  MutationFunction,
  QueryClient
} from '@tanstack/svelte-query';

import type {
  HTTPValidationError,
  RegisterRequest
} from '../../models';

import { customFetch } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Register
 */
export type registerApiAuthRegisterPostResponse201 = {
  data: unknown
  status: 201
}

export type registerApiAuthRegisterPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type registerApiAuthRegisterPostResponseSuccess = (registerApiAuthRegisterPostResponse201) & {
  headers: Headers;
};
export type registerApiAuthRegisterPostResponseError = (registerApiAuthRegisterPostResponse422) & {
  headers: Headers;
};

export type registerApiAuthRegisterPostResponse = (registerApiAuthRegisterPostResponseSuccess | registerApiAuthRegisterPostResponseError)

export const getRegisterApiAuthRegisterPostUrl = () => {




  return `/api/auth/register`
}

export const registerApiAuthRegisterPost = async (registerRequest: RegisterRequest, options?: RequestInit): Promise<registerApiAuthRegisterPostResponse> => {

  return customFetch<registerApiAuthRegisterPostResponse>(getRegisterApiAuthRegisterPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerRequest,)
  }
);}




export const getRegisterApiAuthRegisterPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof registerApiAuthRegisterPost>>, TError,{data: RegisterRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof registerApiAuthRegisterPost>>, TError,{data: RegisterRequest}, TContext> => {

const mutationKey = ['registerApiAuthRegisterPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerApiAuthRegisterPost>>, {data: RegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  registerApiAuthRegisterPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RegisterApiAuthRegisterPostMutationResult = NonNullable<Awaited<ReturnType<typeof registerApiAuthRegisterPost>>>
    export type RegisterApiAuthRegisterPostMutationBody = RegisterRequest
    export type RegisterApiAuthRegisterPostMutationError = HTTPValidationError

    /**
 * @summary Register
 */
export const createRegisterApiAuthRegisterPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof registerApiAuthRegisterPost>>, TError,{data: RegisterRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof registerApiAuthRegisterPost>>,
        TError,
        {data: RegisterRequest},
        TContext
      > => {
      return createMutation(() => ({ ...getRegisterApiAuthRegisterPostMutationOptions(options?.()) }), queryClient);
    }
    /**
 * @summary Login
 */
export type loginApiAuthLoginPostResponse200 = {
  data: unknown
  status: 200
}

export type loginApiAuthLoginPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type loginApiAuthLoginPostResponseSuccess = (loginApiAuthLoginPostResponse200) & {
  headers: Headers;
};
export type loginApiAuthLoginPostResponseError = (loginApiAuthLoginPostResponse422) & {
  headers: Headers;
};

export type loginApiAuthLoginPostResponse = (loginApiAuthLoginPostResponseSuccess | loginApiAuthLoginPostResponseError)

export const getLoginApiAuthLoginPostUrl = () => {




  return `/api/auth/login`
}

export const loginApiAuthLoginPost = async (registerRequest: RegisterRequest, options?: RequestInit): Promise<loginApiAuthLoginPostResponse> => {

  return customFetch<loginApiAuthLoginPostResponse>(getLoginApiAuthLoginPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerRequest,)
  }
);}




export const getLoginApiAuthLoginPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof loginApiAuthLoginPost>>, TError,{data: RegisterRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof loginApiAuthLoginPost>>, TError,{data: RegisterRequest}, TContext> => {

const mutationKey = ['loginApiAuthLoginPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginApiAuthLoginPost>>, {data: RegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  loginApiAuthLoginPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginApiAuthLoginPostMutationResult = NonNullable<Awaited<ReturnType<typeof loginApiAuthLoginPost>>>
    export type LoginApiAuthLoginPostMutationBody = RegisterRequest
    export type LoginApiAuthLoginPostMutationError = HTTPValidationError

    /**
 * @summary Login
 */
export const createLoginApiAuthLoginPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof loginApiAuthLoginPost>>, TError,{data: RegisterRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof loginApiAuthLoginPost>>,
        TError,
        {data: RegisterRequest},
        TContext
      > => {
      return createMutation(() => ({ ...getLoginApiAuthLoginPostMutationOptions(options?.()) }), queryClient);
    }
