/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

/**
 * @summary Register
 */
export const registerApiAuthRegisterPostBodyUsernameMin = 3;
export const registerApiAuthRegisterPostBodyUsernameMax = 40;

export const registerApiAuthRegisterPostBodyPasswordMin = 8;
export const registerApiAuthRegisterPostBodyPasswordMax = 200;

export const RegisterApiAuthRegisterPostBody = zod.object({
	username: zod
		.string()
		.min(registerApiAuthRegisterPostBodyUsernameMin)
		.max(registerApiAuthRegisterPostBodyUsernameMax),
	password: zod.string().min(registerApiAuthRegisterPostBodyPasswordMin).max(registerApiAuthRegisterPostBodyPasswordMax)
});

/**
 * @summary Login
 */
export const loginApiAuthLoginPostBodyUsernameMin = 3;
export const loginApiAuthLoginPostBodyUsernameMax = 40;

export const loginApiAuthLoginPostBodyPasswordMin = 8;
export const loginApiAuthLoginPostBodyPasswordMax = 200;

export const LoginApiAuthLoginPostBody = zod.object({
	username: zod.string().min(loginApiAuthLoginPostBodyUsernameMin).max(loginApiAuthLoginPostBodyUsernameMax),
	password: zod.string().min(loginApiAuthLoginPostBodyPasswordMin).max(loginApiAuthLoginPostBodyPasswordMax)
});

export const LoginApiAuthLoginPostResponse = zod.unknown();
