"""Init

Revision ID: 4e769696f8b6
Revises:
Create Date: 2026-08-08 15:08:24.324582

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e769696f8b6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("proxy_providers", sa.Column("name", sa.String(), nullable=False), sa.PrimaryKeyConstraint("name"))
    op.create_table(
        "proxies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("outbound", sa.JSON(), nullable=False),
        sa.Column("provider_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["provider_name"], ["proxy_providers.name"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("proxies")
    op.drop_table("proxy_providers")
    # ### end Alembic commands ###
