/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

/**
 * @summary Is First Setup Done
 */
export const IsFirstSetupDoneApiMiscIsFirstSetupDoneGetResponse = zod.unknown();
