/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import { customFetch } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Is First Setup Done
 */
export type isFirstSetupDoneApiMiscIsFirstSetupDoneGetResponse200 = {
  data: unknown
  status: 200
}

export type isFirstSetupDoneApiMiscIsFirstSetupDoneGetResponseSuccess = (isFirstSetupDoneApiMiscIsFirstSetupDoneGetResponse200) & {
  headers: Headers;
};
;

export type isFirstSetupDoneApiMiscIsFirstSetupDoneGetResponse = (isFirstSetupDoneApiMiscIsFirstSetupDoneGetResponseSuccess)

export const getIsFirstSetupDoneApiMiscIsFirstSetupDoneGetUrl = () => {




  return `/api/misc/is_first_setup_done`
}

export const isFirstSetupDoneApiMiscIsFirstSetupDoneGet = async ( options?: RequestInit): Promise<isFirstSetupDoneApiMiscIsFirstSetupDoneGetResponse> => {

  return customFetch<isFirstSetupDoneApiMiscIsFirstSetupDoneGetResponse>(getIsFirstSetupDoneApiMiscIsFirstSetupDoneGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getIsFirstSetupDoneApiMiscIsFirstSetupDoneGetQueryKey = () => {
    return [
    `/api/misc/is_first_setup_done`
    ] as const;
    }


export const getIsFirstSetupDoneApiMiscIsFirstSetupDoneGetQueryOptions = <TData = Awaited<ReturnType<typeof isFirstSetupDoneApiMiscIsFirstSetupDoneGet>>, TError = unknown>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof isFirstSetupDoneApiMiscIsFirstSetupDoneGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getIsFirstSetupDoneApiMiscIsFirstSetupDoneGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof isFirstSetupDoneApiMiscIsFirstSetupDoneGet>>> = ({ signal }) => isFirstSetupDoneApiMiscIsFirstSetupDoneGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof isFirstSetupDoneApiMiscIsFirstSetupDoneGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type IsFirstSetupDoneApiMiscIsFirstSetupDoneGetQueryResult = NonNullable<Awaited<ReturnType<typeof isFirstSetupDoneApiMiscIsFirstSetupDoneGet>>>
export type IsFirstSetupDoneApiMiscIsFirstSetupDoneGetQueryError = unknown


/**
 * @summary Is First Setup Done
 */

export function createIsFirstSetupDoneApiMiscIsFirstSetupDoneGet<TData = Awaited<ReturnType<typeof isFirstSetupDoneApiMiscIsFirstSetupDoneGet>>, TError = unknown>(
  options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof isFirstSetupDoneApiMiscIsFirstSetupDoneGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getIsFirstSetupDoneApiMiscIsFirstSetupDoneGetQueryOptions(options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}






